### PR TITLE
modify unity normalization and add unity_continuous

### PR DESCRIPTION
**Pull request by georgievgeorgi**

### CODE REVIEW

**Comment by georgievgeorgi** [comment]
@vedina, `unity_continuous` added
```python
spe.normalize(strategy='unity_continuous')
```

**Comment by vedina** [comment]
ok, but please explain he naming -  why it is unity_continuous - I would prefer "area" 
and none of the other "unity*" are actually normalizing to unity - they normalize to something else

**Comment by georgievgeorgi** [comment]
The values of the bins in a spectrum tell us the number of hits in that particular bin
```c
if (measurement > bin_i_left_boundary && measurement < bin_i_right_boundary)
    bin_i_content ++;
```

If we divide each bin by the total number of particles, we get the relative density for the corresponding boundaries. These relative intensities add to unity. This is true also for uneven bin sizes.

On the other hand, if the histogram is regarded as continuous distribution (which is not), then one should account for the bin widths, because then we will want that `Σ y_i * bin_i_width = 1`. Hence, `_continuous` in the name of the function.

**Comment by vedina** [comment]
-  please include this explanation in the docs
-  still will suggest to add  'area' as a synonym for 'unity_continuous'  , it is normalizing for area regardless of whether the bins are uniform or not

**Comment by georgievgeorgi** [comment]
Exactly, I am afraid that area is widely used term and it might be misleading.
- I agree that `area` and `unity_continuous` are the same and they will work for PDF
- I disagree that doing area normalization on a histogram we will result to density.

Here is a simple example that illustrates what i mean. Merging bins is a particular case of uneven bins sizes.
```
                          ┌─┐
                          │ │
            ┌┐            │ │
            ││┌┐          │ │
          ┌┐││││        ┌┐│ │
          ││││││┌┐      │││ │┌┐
          └┘└┘└┘└┘      └┘└─┘└┘
Events     2 4 3 1       2  7  1
Area       2 4 3 1       2 14  1
Unity     .2.4.3.1      .2 .7 .1
AreaNorm  .2.4.3.1      2/17 14/17 1/17

```

AreaNorm is not correct. It would have been correct, however, in case of continuous distribution.

**Comment by vedina** [comment]
ops, sorry, thought I am replying and  I was editing your post !

**Comment by vedina** [comment]
> Exactly, I am afraid that area is widely used term and it might be misleading.
> 
> * I agree that `area` and `unity_continuous` are the same and they will work for PDF
> * I disagree that doing area normalization on a histogram we will result to density.

Well , this is definition of a density.  Besides, the fact we have a histogram is only due to the measurement artifact .

Will reply on the ASCII art if you put it back ...

**Comment by georgievgeorgi** [comment]
Here is my original message:

Exactly, I am afraid that area is widely used term and it might be misleading.
-   I agree that area and unity_continuous are the same and they will work for PDF
-   I disagree that doing area normalization on a histogram we will result to density.

Here is a simple example that illustrates what i mean. Merging bins is a particular case of uneven bins sizes.
```
                          ┌─┐
                          │ │
            ┌┐            │ │
            ││┌┐          │ │
          ┌┐││││        ┌┐│ │
          ││││││┌┐      │││ │┌┐
          └┘└┘└┘└┘      └┘└─┘└┘
Events     2 4 3 1       2  7  1
Area       2 4 3 1       2 14  1
Unity     .2.4.3.1      .2 .7 .1
AreaNorm  .2.4.3.1      2/17 14/17 1/17
```
AreaNorm is not correct. It would have been correct, however, in case of continuous distribution.

**Comment by vedina** [comment]
> 
> Here is a simple example that illustrates what i mean. Merging bins is a particular case of uneven bins sizes.

You don't specify bins boundaries and it is not clear how can you do area normalization without that.  The bin width i the merged bin will bi sum of the bin widths  of the merged bins. The integral will not change because of the merge.  So I do not agree with the numbers for AreaNorm, they are not calculated properly.

**Comment by georgievgeorgi** [comment]
I think what i am trying to say is that if we divide by the bin width, the "normalized" histogram will no longer has the meaning of histogram. The bin will no longer represent the number of events in those boundaries

**Comment by vedina** [comment]
> I think what i am trying to say is that if we divide by the bin width, the "normalized" histogram will no longer has the meaning of histogram. The bin will no longer represent the number of events in those boundaries

yes and no
a normalized histogram is a density, hence the bin does not represent a number, but the *area* of the bin represents probability of finding the event in the bin range

**Comment by georgievgeorgi** [comment]
Then what happens if we area-normalize a normalized histogram? Should they be equal?

**Comment by vedina** [comment]
> Then what happens if we area-normalize a normalized histogram? Should they be equal?

normalized histogram = area-normalized histogram , so I don't understand the question  ?

**Comment by vedina** [comment]
btw, try the density option https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.hist.html

**Comment by georgievgeorgi** [comment]
The question is what is going to happen if we apply the same area-normalization procedure multiple times. Do we expect that
N(spe) = N(N(spe)) = N¹⁰⁰(spe)

**Comment by vedina** [comment]
It should not change, because area normalization means you are dividing on the area - and if normalized the area is already 1

**Comment by georgievgeorgi** [comment]
```python
import matplotlib.pyplot as plt
import numpy as np
import ramanchada2 as rc2
x = np.array([1, 2, 3, 5, 7, 8, 9])
spe = rc2.spectrum.Spectrum(x=x, y=np.random.uniform(size=x.shape))
fig, ax = plt.subplots(nrows=2)
spe_unity = spe
spe_area = spe
for i in range(1, 10):
    spe_unity = spe_unity.normalize('unity')
    spe_unity.plot(ax=ax[0], label=f'unity$^{i}$')

for i in range(1, 10):
    spe_area = spe_area.normalize('unity_continuous')
    spe_area.plot(ax=ax[1], label=f'area$^{i}$')
    
ax[0].legend(ncol=5)
ax[1].legend(ncol=5)
```

**Comment by vedina** [comment]
btw, if bins are not uniform, this implementation is not correct

```
        res = old_spe.y
        res /= np.sum(res)
        res /= np.diff(old_spe.x_bin_boundaries)
        new_spe.y = res
```

**Comment by vedina** [comment]
> ```python
> import matplotlib.pyplot as plt
> import numpy as np
> import ramanchada2 as rc2
> x = np.array([1, 2, 3, 5, 7, 8, 9])
> spe = rc2.spectrum.Spectrum(x=x, y=np.random.uniform(size=x.shape))
> fig, ax = plt.subplots(nrows=2)
> spe_unity = spe
> spe_area = spe
> for i in range(1, 10):
>     spe_unity = spe_unity.normalize('unity')
>     spe_unity.plot(ax=ax[0], label=f'unity$^{i}$')
> 
> for i in range(1, 10):
>     spe_area = spe_area.normalize('unity_continuous')
>     spe_area.plot(ax=ax[1], label=f'area$^{i}$')
>     
> ax[0].legend(ncol=5)
> ax[1].legend(ncol=5)
> ```

Then there is smth wrong with the implementation or numerical error, theoretically it should not change

**Comment by georgievgeorgi** [comment]
I don't see the problem with that definition, because we want to get unity when we multiply content by bin width `Σ y_i * bin_i_width = 1`
If i am missing something, please advise.

**Comment by vedina** [comment]
> 

yes,

**Comment by vedina** [comment]
> I don't see the problem with that definition, because we want to get unity when we multiply content by bin width `Σ y_i * bin_i_width = 1` If i am missing something, please advise.

not (yet) sure what is wrong

print(sum(x * y for x, y in zip(spe_area.x_bin_boundaries,spe_area.y)))  

does not return always sharp 1, sometimes .99 and sometimes 1.0000000000000002

**Comment by georgievgeorgi** [comment]
Yes, the area is 1.
```python
np.sum(spe_area.y*np.diff(spe_area.x_bin_boundaries))
```
I divide by Σy, after that by Δx, because i want when multiply by Δx to get Σ(y / Σy) = Σy / Σy = 1
```python
res = spe.y
res /= np.sum(res)
res /= np.diff(old_spe.x_bin_boundaries)
```
The problem with multiple successive normalization is that we keep multiplying by Δx, which is never undone.

I think that some amount of confusion may come from the fact that by this
```
   ┌───┐   
   │   │┌─┐           
   │   ││ │           
┌─┐│   ││ │           
│ ││   ││ │           
│ ││   ││ │           
└─┘└───┘└─┘           
```                  
we actually mean this 
```
    ─┼─               
     │   ┼            
     │   │ 
 ┼   │   │            
 │   │   │ 
 │   │   │     
 ```

**Comment by vedina** [comment]
Could be a numerical error.  This is more stable (and I would say simpler) 

```
import matplotlib.pyplot as plt
import numpy as np
import ramanchada2 as rc2

def area(spe):
    return sum(x * y for x, y in zip(np.diff(spe_area.x_bin_boundaries),spe_area.y))

x = np.array([1, 2, 3, 5, 7, 8, 9])
spe = rc2.spectrum.Spectrum(x=x, y=np.random.uniform(size=x.shape))
fig, ax = plt.subplots(nrows=2)
spe_unity = spe
spe_area = spe
for i in range(1, 10):
    spe_unity = spe_unity.normalize('unity')
    spe_unity.plot(ax=ax[0], label=f'unity$^{i}$')

for i in range(1, 10):
    print(sum(x * y for x, y in zip(np.diff(spe_area.x_bin_boundaries),spe_area.y)))
    spe.y = spe.y / area(spe)
    spe_area.plot(ax=ax[1], label=f'area$^{i}$')
    
ax[0].legend(ncol=5)
ax[1].legend(ncol=5)
```

**Comment by vedina** [comment]
> ```python
> import matplotlib.pyplot as plt
> import numpy as np
> import ramanchada2 as rc2
> x = np.array([1, 2, 3, 5, 7, 8, 9])
> spe = rc2.spectrum.Spectrum(x=x, y=np.random.uniform(size=x.shape))
> fig, ax = plt.subplots(nrows=2)
> spe_unity = spe
> spe_area = spe
> for i in range(1, 10):
>     spe_unity = spe_unity.normalize('unity')
>     spe_unity.plot(ax=ax[0], label=f'unity$^{i}$')
> 
> for i in range(1, 10):
>     spe_area = spe_area.normalize('unity_continuous')
>     spe_area.plot(ax=ax[1], label=f'area$^{i}$')
>     
> ax[0].legend(ncol=5)
> ax[1].legend(ncol=5)
> ```

I am aware of this,  think the unstability is due to numerical error  - this is printout from the original snippet above

1.0
0.9999999999999999
1.0
0.9999999999999998
0.9999999999999999
1.0
1.0
1.0

**Comment by vedina** [comment]
OK, here is the suggestion 

```
    if strategy == 'unity_continuous' | strategy == 'area ':
        area = sum(x * y for x, y in zip(np.diff(old_spe.x_bin_boundaries),old_spe.y))
        new_spe.y = old_spe.y / area
```

**Review by vedina — COMMENTED** [review]
ok

**Pull request merged**
