### PR TITLE
Improvements and bugfixes

### PR DESCRIPTION
**Pull request by georgievgeorgi**

### CODE REVIEW

**Comment by kerberizer** [comment]
@vedina What should we do with this PR?

**Comment by vedina** [comment]
merge, but later , let me find time to look at it

**Review by vedina — APPROVED** [review]

**Comment by kerberizer** [comment]
@vedina Since you approved the changes, should I go ahead and merge it now? I already checked that there are no conflicts with nexusformat.

**Comment by vedina** [comment]
yes, pls merge

**Pull request merged**
