### PR TITLE
Migrate to numpy 2

### PR DESCRIPTION
**Pull request by georgievgeorgi**
- `np.infty` substituted with `np.inf`
- use `rng.bit_generator.state` to get and set states

### CODE REVIEW

**Comment by georgievgeorgi** [comment]
TODO: make sure it works with numpy 1

**Comment by vedina** [comment]
please check if it works with both numpy<2 & numpy>=2

**Comment by georgievgeorgi** [comment]
All the tests pass successfully with both numpy<2 and numpy>=2. So the PR seems safe to be merged.

**Comment by kerberizer** [comment]
@georgievgeorgi Thank you very much for the work on this! Do you think it is realistic to cover with tests the few remaining statements per the [coverage report](https://github.com/h2020charisma/ramanchada2/pull/128#issuecomment-2204176582) above?

**Comment by georgievgeorgi** [comment]
In the tests i found that i doubled the tests for `add_gaussian_noise` and missed the `add_poisson_noise` (@kerberizer, thank you for drawing my attention there). Currently i am playing with tests for `argmin2d`.

**Comment by georgievgeorgi** [comment]
@kerberizer, could you please review and merge this pull request

**Comment by kerberizer** [comment]
@georgievgeorgi I was under the impression that you wanted to add more tests. Are we going to aim for 100% test coverage? It's one single statement, but still.

**Comment by georgievgeorgi** [comment]
I understand. I fixed a copy-paste issue and added an extra test which covers `argmin2d`. Adding a test for `align_shift`, however, is not that straight forward. With the provided tests the code coverage is improved anyway and as the main purpose of the pull request is not to provide tests but to fix the numpy2 issues, i think it can be merged.

**Pull request merged**
