### PR TITLE
Add convertion script for Thermo Nicolet spa and spg files

### PR DESCRIPTION
**Pull request by georgievgeorgi**

### CODE REVIEW

**Comment by georgievgeorgi** [comment]
@kerberizer, is this the right place for the `spg` converter?

**Comment by kerberizer** [comment]
> @kerberizer, is this the right place for the `spg` converter?

I'd say rather not. Script support has been somewhat counterintuitive for me, but here's how it works: https://setuptools.pypa.io/en/latest/userguide/entry_point.html#console-scripts

That's if you want the users to be able to run the script directly from the console. If you just want to add it as a file in the package, it's much easier of course, but then users will have to browse through `site_packages` to find it.

**Comment by georgievgeorgi** [comment]
It should be better now. What do you think? Do you have any other suggestions/comments?

**Comment by kerberizer** [comment]
> @kerberizer It should be better now. What do you think? Do you have any other suggestions/comments?

I think it looks great. Didn't know that you could cast an assignment into a dictionary, too. :)

**Comment by georgievgeorgi** [comment]
> `<name> = <package_or_module>[:<object>[.<attr>[.<nested-attr>]*]]`
> where <package_or_module> can contain . in the case of sub-modules or sub-packages

from [here](https://setuptools.pypa.io/en/latest/userguide/entry_point.html#entry-points-syntax)

**Pull request merged**
