### PR TITLE
Alternative Ne/Si calibration

### PR DESCRIPTION
**Pull request by georgievgeorgi**

### CODE REVIEW

**Comment by vedina** [comment]
- haven't tested the code yet 
- is there an example how one saves/loads the calibration and applies it to other spectra without deriving it every time

**Comment by georgievgeorgi** [comment]
```python
def neon_calibration(ne_cm_1: Spectrum,
                     wl: Literal[514, 532, 633, 785]):

def silicon_calibration(si_nm: Spectrum,
                        wl: Literal[514, 532, 633, 785]):

def neon_silicon_calibration(ne_cm_1: Spectrum,
                             si_cm_1: Spectrum,
                             wl: Literal[514, 532, 633, 785]):
```

All these functions return splines, which later can be applied with `scale_xaxis_fun()`:
```python
cal = neon_silicon_calibration(ne_cm_1, si_cm_1, wl)
ps_cal = ps.scale_xaxis_fun(cal)
```

The calibration is not yet saveable using standard rc2 tools.

**Comment by georgievgeorgi** [comment]
@vedina, all tests are passing now. The disabled tests in `calibrationmodel` are enabled now.

**Review by vedina — APPROVED** [review]

**Comment by vedina** [comment]
ok, let's merge @kerberizer

**Pull request merged**
